on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: |
          install.packages("devtools")
          devtools::install()
        shell: Rscript {0}

      - name: Deploy package
        run: |
          if (!git_has_remote_branch("origin", "gh-pages")) {
            old_branch <- git_current_branch()
            git("checkout", "--orphan", "gh-pages")
            git("rm", "-rf", "--quiet", ".")
            git("commit", "--allow-empty", "-m", "Initializing gh-pages branch")
            git("push", "origin", "HEAD:gh-pages")
            git("checkout", old_branch)
          }
          git("config", "--global", "user.email", "info@inbo.be")
          git("config", "--global", "user.name", "INBO")
          pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
